
services:
  postgres:
    container_name: postgres_rating_db
    image: "postgres:latest"
    environment:
      POSTGRES_DB: ratings_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: j@vacefer2005
    ports:
      - "1115:5432"
    volumes:
      - ratings_db:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis-container-rating
    ports:
      - "6381:6379"

volumes:
  ratings_db:
networks:
  default:
    name: rating_network
